import React from 'react';
import { 
  Dumbbell, 
  BookOpen, 
  GlassWater, 
  Moon, 
  Sun, 
  Code, 
  Music, 
  Briefcase, 
  Coffee,
  Heart,
  Zap,
  Smile,
  CheckCircle2,
  Flame,
  Star,
  Trophy,
  Target,
  Leaf,
  Bike,
  Gamepad2,
  Tv,
  Plane,
  Car,
  Utensils,
  Droplets,
  Palette,
  Smartphone,
  ShoppingBag
} from 'lucide-react';

export const ICONS: Record<string, React.ReactNode> = {
  fitness: <Dumbbell />,
  reading: <BookOpen />,
  water: <GlassWater />,
  sleep: <Moon />,
  morning: <Sun />,
  code: <Code />,
  music: <Music />,
  work: <Briefcase />,
  coffee: <Coffee />,
  health: <Heart />,
  energy: <Zap />,
  mindfulness: <Smile />,
  star: <Star />,
  trophy: <Trophy />,
  target: <Target />,
  leaf: <Leaf />,
  bike: <Bike />,
  gaming: <Gamepad2 />,
  tv: <Tv />,
  travel: <Plane />,
  car: <Car />,
  food: <Utensils />,
  hygiene: <Droplets />,
  art: <Palette />,
  social: <Smartphone />,
  shopping: <ShoppingBag />,
};

export const ICON_KEYS = Object.keys(ICONS);

export const COLORS = [
  'bg-sky-500',
  'bg-blue-500',
  'bg-indigo-500',
  'bg-violet-500',
  'bg-purple-500',
  'bg-fuchsia-500',
  'bg-cyan-500',
  'bg-teal-500',
  'bg-emerald-500',
  'bg-green-500',
  'bg-lime-500',
  'bg-yellow-500',
  'bg-amber-500',
  'bg-orange-500',
  'bg-red-500',
  'bg-rose-500',
  'bg-pink-500',
  'bg-slate-500',
];